#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'shadowsocks==3.0.0','console_scripts','ssserver'
__requires__ = 'shadowsocks==3.0.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('shadowsocks==3.0.0', 'console_scripts', 'ssserver')()
    )
